-- ***********************************
-- SQL BASIC
-- ***********************************

USE [QLHD]
GO

--====================================
---TASK 1: SELECT
--====================================
	--1: TỪ BẢNG CTHD, TÌM RA CÁC MÃ SẢN PHẨM CÓ TỔNG SẢN LƯỢNG BÁN HÀNG LỚN HƠN 100
		SELECT MASP,
			   SUM(SL) AS TONGSL
		FROM QLHD..CTHD
		GROUP BY MASP
		HAVING SUM(SL)>100

	--2: TỪ BẢNG HOADON, TÌM RA NHÂN VIÊN BÁN ĐƯỢC NHIỀU HÓA ĐƠN NHẤT (SỐ LƯỢNG) HOẶC CÓ TỔNG TRỊ GIÁ HỢP ĐỒNG LỚN NHẤT (TRI GIÁ)
		-- NHÂN VIÊN BÁN ĐƯỢC NHIỀU HÓA ĐƠN NHẤT (SỐ LƯỢNG)
		SELECT TOP 1 MANV,
				   COUNT(DISTINCT(SOHD)) AS SOHOADON
		FROM QLHD..HOADON
		GROUP BY MANV
		ORDER BY SOHOADON DESC

		--NHÂN VIÊN CÓ TỔNG TRỊ GIÁ HỢP ĐỒNG LỚN NHẤT (TRI GIÁ)
		SELECT TOP 1 MANV,
				   SUM(CONVERT(FLOAT,TRIGIA)) AS TONGTRIGIA
		FROM QLHD..HOADON
		GROUP BY MANV
		ORDER BY TONGTRIGIA DESC


	--3: TỪ BẢNG HOADON THỐNG KÊ SỐ LẦN MUA HÀNG VÀ TRỊ GIÁ TƯƠNG ỨNG ĐỔI VỚI MỖI KHÁCH	HÀNG 
		SELECT MAKH,
			COUNT(*) AS SOLANMUA,
			SUM(TRIGIA) AS TONGTRIGIA
		FROM QLHD..HOADON
		GROUP BY MAKH

	--4. TỪ BẢNG CTHD, TÌM CÁC SẢN PHẨM BÁN ĐƯỢC SỐ LƯỢNG NHIỀU NHẤT BẰNG ÍT NHẤT 2 CÁCH
	-- CÁCH 1
		SELECT TOP 1 MASP,
				   SUM(SL) AS TONGSL
		FROM QLHD..CTHD
		GROUP BY MASP
		ORDER BY TONGSL DESC 

	-- CÁCH 2
		SELECT MASP,
			   SUM(SL) AS TONGSL
		FROM QLHD..CTHD
		GROUP BY MASP
		HAVING SUM(SL)=
		  (SELECT MAX(SL)
		   FROM
			 (SELECT MASP,
					 SUM(SL) AS SL
			  FROM QLHD..CTHD
			  GROUP BY MASP) a)

--====================================			
--TASK 2: SELECT, NESTED QUERY, ALTER TABLE, UPDATE, SELECT INTO
--====================================
	--1. TỪ BẢNG HOADON TÌM TOP 3 KH CÓ NHIỀU ĐƠN HÀNG NHẤT TRONG NĂM 2006 
	-- VÀ LẤY RA TÊN KHÁCH HÀNG ĐÓ (TỪ BẢNG KHACHHANG)

	--CÁCH 1: SỬ DỤNG GROUP BY VÀ TRUY VẤN LỒNG
		SELECT MAKH,
			   HOTEN
		FROM QLHD..KHACHHANG
		WHERE MAKH IN
			(SELECT TOP 3 MAKH
			 FROM QLHD..HOADON
			 WHERE YEAR(NGHD)=2006
			 GROUP BY MAKH
			 ORDER BY COUNT(*) DESC)

	--CÁCH 2: TẠO MỘT BẢNG BACKUP TỪ BẢNG HOADON ĐẶT TÊN LÀ HOADON_BK,
	-----SAU ĐÓ UPDATE TÊN KH TƯƠNG ỨNG VỚI MÃ KH TRONG BẢNG HOADON_BK TỪ BẢNG KHACHHANG,
	-----SỬ DỤNG GROUP BY 
		SELECT * INTO QLHD..HOADON_BK
		FROM QLHD..HOADON
	
		ALTER TABLE QLHD..HOADON_BK ADD HOTEN VARCHAR(40)
	
		SELECT *
		FROM QLHD..HOADON_BK
	
		UPDATE QLHD..HOADON_BK
		SET QLHD..HOADON_BK.HOTEN=QLHD..KHACHHANG.HOTEN
		FROM QLHD..KHACHHANG
		WHERE QLHD..HOADON_BK.MAKH=QLHD..KHACHHANG.MAKH --(22 rows affected)

		SELECT TOP 3 MAKH,
					 HOTEN
		FROM QLHD..HOADON_BK WHERE YEAR(NGHD)=2006
		GROUP BY MAKH,
				 HOTEN
		ORDER BY COUNT(*) DESC


	--2: TỪ BẢNG CTHD TÌM RA 3 MẶT HÀNG BÁN CHẠY NHẤT (TỔNG SL) 
	-- VÀ LẤY RA TÊN SẢN PHẨM ĐÓ (TỪ BẢNG SANPHAM)

	--CÁCH 1: SỬ DỤNG GROUP BY VÀ TRUY VẤN LỒNG
		SELECT TENSP
		FROM QLHD..SANPHAM
		WHERE MASP IN
			(SELECT TOP 3 MASP
			 FROM QLHD..CTHD
			 GROUP BY MASP
			 ORDER BY SUM(SL) DESC)

	--CÁCH 2: TẠO MỘT BẢNG BACKUP TỪ BẢNG CTHD ĐẶT TÊN LÀ CTHD_BK, 
	----SAU ĐÓ UPDATE TÊN SP TƯƠNG ỨNG VỚI MÃ SP TRONG CTHD_BK TỪ BẢNG SANPHAM,
	----SỬ DỤNG GROUP BY 
		SELECT * INTO QLHD..CTHD_BK
		FROM QLHD..CTHD 
		--(51 rows affected)

		ALTER TABLE QLHD..CTHD_BK ADD TENSP VARCHAR(40)
		UPDATE QLHD..CTHD_BK
		SET QLHD..CTHD_BK.TENSP = QLHD..SANPHAM.TENSP
		FROM QLHD..SANPHAM
		WHERE QLHD..CTHD_BK.MASP= QLHD..SANPHAM.MASP 
		--(49 rows affected)

		SELECT TOP 3 TENSP,
					 MASP,
					 SUM (SL) AS TONGSL
		FROM QLHD..CTHD_BK
		GROUP BY MASP,
				 TENSP
		ORDER BY SUM(SL) DESC

	--3. TỪ BẢNG NHANVIEN, TÌM SỐ LƯỢNG NHÂN VIÊN TUYỂN HÀNG NĂM 
	-- NGVL: NGÀY VÀO LÀM VIỆC 
	-- SỬ DỤNG YEAR ()
		SELECT YEAR(NGVL) AS YEARVL,
			   COUNT(*) AS SOLUONGTUYEN
		FROM QLHD..NHANVIEN
		GROUP BY YEAR(NGVL)

	--4. TỪ BẢNG HOADON, THỐNG KÊ SỐ LƯỢNG HÓA ĐƠN BÁN ĐƯỢC 
	-- VÀ TỔNG TRỊ GIÁ TRONG MỖI THÁNG TRONG NĂM 2006 (SỬ DỤNG MONTH (), YEAR ())
	-- GROUP BY THEO MONTH(NGHD)
		
		SELECT MONTH(NGHD) AS THANG,
				COUNT (*) AS TONGHD,
				SUM(TRIGIA) AS TONGTRIGIA
		FROM QLHD..HOADON
		WHERE YEAR(NGHD)=2006
		GROUP BY MONTH(NGHD)

	--5. TỪ BẢNG HOADON, THỐNG KÊ DOANH SỐ BÁN HÀNG (TỔNG TRỊ GIÁ) 
	-- CỦA MỖI NHÂN VIÊN TRONG MỖI THÁNG TRONG NĂM 2006
	-- GỢI Ý GROUP BY MONTH (NGHD), MANV
		SELECT MONTH(NGHD) AS THANG,
			   MANV,
			   SUM(TRIGIA) AS TONGTRIGIA
		FROM QLHD..HOADON
		WHERE YEAR(NGHD)=2006
		GROUP BY MONTH(NGHD),
				 MANV
		ORDER BY MONTH(NGHD) ASC
 
	 --6. TỪ BẢNG CTHD_BK LẤY RA MÃ BÚT BI BÁN ĐƯỢC NHIỀU NHẤT 
	 -- VÀ LẤY RA TÊN NUOCSX MÃ BÚT BI ĐÓ TỪ BẢNG SẢN PHẨM

		SELECT MASP,
			   NUOCSX
		FROM QLHD..SANPHAM
		WHERE MASP IN
			(SELECT TOP 1 MASP
			 FROM QLHD..CTHD_BK
			 WHERE TENSP='BUT BI'
			 GROUP BY MASP
			 ORDER BY SUM(SL) DESC)

--====================================
--TASK 3: UNION ALL
--====================================
	--TẠO BẢNG BACKUP DỮ LIỆU TỪ BẢNG SANPHAM 
	-- BIẾT RẰNG GIÁ SẢN PHẨM LƠN HƠN 5000 ĐẶT TÊN LÀ QLHD..A1
		SELECT * 
		INTO QLHD..A1
		FROM QLHD..SANPHAM
		WHERE GIA>5000


	--TẠO BẢNG BACKUP DỮ LIỆU TỪ BẢNG SANPHAM 
	-- BIẾT RẰNG GIÁ SẢN PHẨM LƠN HƠN 5000 ĐẶT TÊN LÀ QLHD..A2
		SELECT * 
		INTO QLHD..A2
		FROM QLHD..SANPHAM
		WHERE GIA>5000

	--SỬ DỤNG UNION ALL VÀ UNION NỐI HAI BẢNG LẠI VỚI NHAU VÀ NOTE SỐ BẢN GHI ẢNH HƯỞNG 
		SELECT * FROM QLHD..A1
		UNION ALL
		SELECT * FROM QLHD..A2
		-- 30 rows



